name: Deploy python

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python main.py
#      - name: Import GPG key for docs deployment signing
#        id: import_gpg
#        uses: crazy-max/ghaction-import-gpg@v3.0.2
#        with:
#          gpg-private-key: ${{ secrets.DOCS_GPG_PRIV_KEY }}
#          # Set GPG signing keyID for this Git repository
#          git-user-signingkey: true
#          # Sign all commits automatically.
#          git-commit-gpgsign: true
#      - name: Print imported GPG key details
#        run: |
#          echo "fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
#          echo "keyid:       ${{ steps.import_gpg.outputs.keyid }}"
#          echo "name:        ${{ steps.import_gpg.outputs.name }}"
#          echo "email:       ${{ steps.import_gpg.outputs.email }}"
#      - name: Deploy Docs
#        uses: JamesIves/github-pages-deploy-action@3.7.1
#        with:
#          ACCESS_TOKEN: ${{ secrets.DOCS_GH_TOKEN }}
#          BRANCH: gh-pages
#          FOLDER: "web"
#          CLEAN: false # don't clean so we can also use tags
#          GIT_CONFIG_NAME: "StickyAPI Docs Deployment"
#          GIT_CONFIG_EMAIL: ${{ secrets.DOCS_GH_EMAIL }}